/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
/**
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Default Live API model to use
 */
export const DEFAULT_LIVE_API_MODEL =
  'gemini-2.5-flash-native-audio-preview-12-2025';

export const DEFAULT_VOICE = 'Aoede';

export const DEFAULT_LANGUAGE = 'Flemish';

export const DEFAULT_NUANCE = 'Casual';

export const DEFAULT_USER_NAME = 'Boss';

export const DEFAULT_AGENT_NAME = 'Beatrice';

export const AVAILABLE_NUANCES = [
  'Casual',
  'Professional',
  'Technical',
  'Emotional',
  'Formal',
  'Playful'
];

export interface VoiceOption {
  name: string;
  alias: string;
}

export const SUPERHERO_VOICES: VoiceOption[] = [
  { name: 'Aoede', alias: 'Wonder Woman' },
  { name: 'Zephyr', alias: 'Spider-Man' },
  { name: 'Puck', alias: 'Deadpool' },
  { name: 'Charon', alias: 'Batman' },
  { name: 'Luna', alias: 'Black Widow' },
  { name: 'Nova', alias: 'Captain Marvel' },
  { name: 'Kore', alias: 'Supergirl' },
  { name: 'Fenrir', alias: 'Wolverine' },
  { name: 'Leda', alias: 'Jean Grey' },
  { name: 'Orus', alias: 'Thor' },
  { name: 'Callirrhoe', alias: 'Scarlet Witch' },
  { name: 'Autonoe', alias: 'Rogue' },
  { name: 'Enceladus', alias: 'Iron Man' },
  { name: 'Iapetus', alias: 'Captain America' },
  { name: 'Umbriel', alias: 'Black Panther' },
  { name: 'Algieba', alias: 'Doctor Strange' },
  { name: 'Despina', alias: 'Storm' },
  { name: 'Erinome', alias: 'Gamora' },
  { name: 'Algenib', alias: 'The Flash' },
  { name: 'Rasalgethi', alias: 'The Hulk' },
  { name: 'Laomedeia', alias: 'Invisible Woman' },
  { name: 'Achernar', alias: 'Aquaman' },
  { name: 'Alnilam', alias: 'Green Lantern' },
  { name: 'Schedar', alias: 'Hawkeye' },
  { name: 'Gacrux', alias: 'Daredevil' },
  { name: 'Pulcherrima', alias: 'Starfire' },
  { name: 'Achird', alias: 'Nightwing' },
  { name: 'Zubenelgenubi', alias: 'Shazam' },
  { name: 'Vindemiatrix', alias: 'Raven' },
  { name: 'Sadachbia', alias: 'Batgirl' },
  { name: 'Sadaltager', alias: 'Cyborg' },
  { name: 'Sulafat', alias: 'Martian Manhunter' }
];

export const AVAILABLE_VOICES = SUPERHERO_VOICES.map(v => v.name);

// ─── MobileUse AI Engine Provider Presets ───────────────────────

export interface AiProviderPreset {
  alias: string;
  label: string;
  baseUrl: string;
  model: string;
  apiKey: string;
}

export const AI_PROVIDER_PRESETS: AiProviderPreset[] = [
  {
    alias: 'ollama',
    label: 'Ollama Local',
    baseUrl: 'http://127.0.0.1:11434/v1',
    model: 'eburon-code-fast:latest',
    apiKey: 'ollama',
  },
  {
    alias: 'opencode',
    label: 'Opencode',
    baseUrl: 'http://127.0.0.1:4096/v1',
    model: 'opencode/deepseek-v4-flash-free',
    apiKey: 'dummy',
  },
  {
    alias: 'ollama-cloud',
    label: 'Ollama Cloud',
    baseUrl: 'https://api.ollama.ai/v1',
    model: 'glm-5.2:cloud',
    apiKey: '',
  },
  {
    alias: 'gemini',
    label: 'Gemini API',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai/',
    model: 'gemini-3.1-flash-lite',
    apiKey: '',
  },
  {
    alias: 'freebuff',
    label: 'Freebuff',
    baseUrl: 'http://127.0.0.1:4096/v1',
    model: 'opencode/deepseek-v4-flash-free',
    apiKey: '',
  },
  {
    alias: 'groq',
    label: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    model: 'openai/gpt-oss-120b',
    apiKey: '',
  },
];

export const DEFAULT_AI_ALIAS = 'ollama';
export const DEFAULT_AI_BASE_URL = 'http://127.0.0.1:11434/v1';
export const DEFAULT_AI_MODEL = 'eburon-code-fast:latest';
export const DEFAULT_AI_API_KEY = 'ollama';

export const AVAILABLE_LANGUAGES = [
  'Flemish',
  'Abkhaz',
  'Acehnese',
  'Acholi',
  'Afar',
  'Afrikaans',
  'Albanian',
  'Alur',
  'Amharic',
  'Arabic',
  'Armenian',
  'Assamese',
  'Avar',
  'Awadhi',
  'Aymara',
  'Azerbaijani',
  'Balinese',
  'Baluchi',
  'Bambara',
  'Baoulé',
  'Bashkir',
  'Basque',
  'Batak Karo',
  'Batak Simalungun',
  'Batak Toba',
  'Belarusian',
  'Bemba',
  'Bengali',
  'Betawi',
  'Bhojpuri',
  'Bikol',
  'Bosnian',
  'Breton',
  'Bulgarian',
  'Buryat',
  'Cantonese',
  'Catalan',
  'Cebuano',
  'Chamorro',
  'Chechen',
  'Chichewa',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Chuukese',
  'Chuvash',
  'Corsican',
  'Crimean Tatar (Cyrillic)',
  'Crimean Tatar (Latin)',
  'Croatian',
  'Czech',
  'Danish',
  'Dari',
  'Dhivehi',
  'Dinka',
  'Dogri',
  'Dombe',
  'Dutch',
  'Dyula',
  'Dzongkha',
  'English',
  'Esperanto',
  'Estonian',
  'Ewe',
  'Faroese',
  'Fijian',
  'Filipino',
  'Finnish',
  'Fon',
  'French',
  'French (Canada)',
  'Frisian',
  'Friulian',
  'Fulani',
  'Ga',
  'Galician',
  'Georgian',
  'German',
  'Greek',
  'Guarani',
  'Gujarati',
  'Haitian Creole',
  'Hakha Chin',
  'Hausa',
  'Hawaiian',
  'Hebrew',
  'Hiligaynon',
  'Hindi',
  'Hmong',
  'Hungarian',
  'Hunsrik',
  'Iban',
  'Icelandic',
  'Igbo',
  'Ilocano',
  'Indonesian',
  'Inuktut (Latin)',
  'Inuktut (Syllabics)',
  'Irish',
  'Italian',
  'Jamaican Patois',
  'Japanese',
  'Javanese',
  'Jingpo',
  'Kalaallisut',
  'Kannada',
  'Kanuri',
  'Kapampangan',
  'Kazakh',
  'Khasi',
  'Khmer',
  'Kiga',
  'Kikongo',
  'Kinyarwanda',
  'Kituba',
  'Kokborok',
  'Komi',
  'Konkani',
  'Korean',
  'Krio',
  'Kurdish (Kurmanji)',
  'Kurdish (Sorani)',
  'Kyrgyz',
  'Lao',
  'Latgalian',
  'Latin',
  'Latvian',
  'Ligurian',
  'Limburgish',
  'Lingala',
  'Lithuanian',
  'Lombard',
  'Luganda',
  'Luo',
  'Luxembourgish',
  'Macedonian',
  'Madurese',
  'Maithili',
  'Makassar',
  'Malagasy',
  'Malay',
  'Malay (Jawi)',
  'Malayalam',
  'Maltese',
  'Mam',
  'Manx',
  'Maori',
  'Marathi',
  'Marshallese',
  'Marwadi',
  'Mauritian Creole',
  'Meadow Mari',
  'Meiteilon (Manipuri)',
  'Minang',
  'Mizo',
  'Mongolian',
  'Myanmar (Burmese)',
  'Nahuatl (Eastern Huasteca)',
  'Ndau',
  'Ndebele (South)',
  'Nepalbhasa (Newari)',
  'Nepali',
  'NKo',
  'Norwegian',
  'Nuer',
  'Occitan',
  'Odia (Oriya)',
  'Oromo',
  'Ossetian',
  'Pangasinan',
  'Papiamento',
  'Pashto',
  'Persian',
  'Polish',
  'Portuguese (Brazil)',
  'Portuguese (Portugal)',
  'Punjabi (Gurmukhi)',
  'Punjabi (Shahmukhi)',
  'Quechua',
  'Qʼeqchiʼ',
  'Romani',
  'Romanian',
  'Rundi',
  'Russian',
  'Sami (North)',
  'Samoan',
  'Sango',
  'Sanskrit',
  'Santali (Latin)',
  'Santali (Ol Chiki)',
  'Scots Gaelic',
  'Sepedi',
  'Serbian',
  'Sesotho',
  'Seychellois Creole',
  'Shan',
  'Shona',
  'Sicilian',
  'Silesian',
  'Sindhi',
  'Sinhala',
  'Slovak',
  'Slovenian',
  'Somali',
  'Spanish',
  'Sundanese',
  'Susu',
  'Swahili',
  'Swati',
  'Swedish',
  'Tahitian',
  'Tajik',
  'Tamazight',
  'Tamazight (Tifinagh)',
  'Tamil',
  'Tatar',
  'Telugu',
  'Tetum',
  'Thai',
  'Tibetan',
  'Tigrinya',
  'Tiv',
  'Tok Pisin',
  'Tongan',
  'Tshiluba',
  'Tsonga',
  'Tswana',
  'Tulu',
  'Tumbuka',
  'Turkish',
  'Turkmen',
  'Tuvan',
  'Twi',
  'Udmurt',
  'Ukrainian',
  'Urdu',
  'Uyghur',
  'Uzbek',
  'Venda',
  'Venetian',
  'Vietnamese',
  'Waray',
  'Welsh',
  'Wolof',
  'Xhosa',
  'Yakut',
  'Yiddish',
  'Yoruba',
  'Yucatec Maya',
  'Zapotec',
  'Zulu'
];
